server:
  port: 7001
eureka:
  client:
    instance:
      hostname: config
    healthcheck:
      enabled: true
    service-url:
      defaultZone: http://localhost:8001/eureka
spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Dhcy/config.git
          search-paths: /**
          username: Dhcy
          password: 5955588abc


